#
# Component Makefile
#

COMPONENT_DEPENDS := freertos

COMPONENT_ADD_INCLUDEDIRS += include
COMPONENT_ADD_INCLUDEDIRS += ports/freertos
COMPONENT_PRIV_INCLUDEDIRS += src

COMPONENT_SRCDIRS += ports/freertos
COMPONENT_SRCDIRS += src/qf
COMPONENT_SRCDIRS += include

CFLAGS += -DQPC_ESP32_PORT

ifdef CONFIG_QPC_QSPY_ENABLE
COMPONENT_SRCDIRS += src/qs
CFLAGS += -DQ_SPY
endif